version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000

  memcached1:
    image: memcached
  memcached2:
    image: memcached
  memcached3:
    image: memcached

  php-fpm:
    build: docker/php-fpm
    env_file: 
      - .env
      - .env.local
    volumes:
      - ./:/var/www

  nginx:
    depends_on:
      - php-fpm
    image: nginx:alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 80:80

  initializer:
    depends_on:
      - dynamodb
    image: amazon/aws-cli
    env_file: 
      - .env.local
    volumes:
      - ./docker/initializer:/aws/scripts
    entrypoint: bash
    command: /aws/scripts/init.sh