service: ImageGenerator

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::images-dfd/*
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:eu-west-1:*:table/ImageList

layers:
  Source:
    path: lambda-layer
    package:
      include:
        - 'nodejs/node_modules/**'

package:
  include:
    - 'index.js'
  exclude:
    - '**/*'

resources:
  Resources:
    ImageGeneratorQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: ImageGenerator-${self:provider.stage}
    
    ImageGeneratorApplication:
      Type: AWS::ElasticBeanstalk::Application
      Properties:
        ApplicationName: ImageGeneratorApplication-${self:provider.stage}
        Description: ImageGenerator Application

    ImageGeneratorApplicationVersion:
      DependsOn:
        - ImageGeneratorApplication
      Type: AWS::ElasticBeanstalk::ApplicationVersion
      Properties: 
        ApplicationName:
          Ref: ImageGeneratorApplication
        SourceBundle: 
          S3Bucket: ${opt:S3Bucket}
          S3Key: ${opt:S3ApplicationVersionKey}
    
    ImageGeneratorEnvironment:
      DependsOn:
        - ImageGeneratorQueue
        - ImageGeneratorApplication
      Type: AWS::ElasticBeanstalk::Environment
      Properties:
        ApplicationName:
          Ref: ImageGeneratorApplication
        EnvironmentName: ImageGeneratorEnvironment-${self:provider.stage}
        Description: ImageGenerator Environment
        SolutionStackName: 64bit Amazon Linux 2 v3.1.1 running PHP 7.3
        VersionLabel: 
          Ref: ImageGeneratorApplicationVersion
        OptionSettings:
          - Namespace: aws:autoscaling:asg
            OptionName: MinSize
            Value: 1
          - Namespace: aws:autoscaling:asg
            OptionName: MaxSize
            Value: 3
          - Namespace: aws:autoscaling:launchconfiguration
            OptionName: InstanceType
            Value: t2.small
          - Namespace: aws:autoscaling:launchconfiguration
            OptionName: EC2KeyName
            Value: ${env:EC2_KEYNAME}
          - Namespace: aws:autoscaling:launchconfiguration
            OptionName: IamInstanceProfile
            Value: aws-elasticbeanstalk-ec2-role
          - Namespace: aws:elasticbeanstalk:container:php:phpini
            OptionName: document_root
            Value: /public
          - Namespace: aws:elasticbeanstalk:application:environment
            OptionName: SQS_URL
            Value:
              Ref: ImageGeneratorQueue
          - Namespace: aws:elasticbeanstalk:application:environment
            OptionName: MEMCACHED_ADDRESS
            Value:
              Fn::GetAtt: [ImageGeneratorCache, ConfigurationEndpoint.Address]
          - Namespace: aws:elasticbeanstalk:application:environment
            OptionName: DYNAMODB_TABLE
            Value: ImageList-${self:provider.stage}

    ImageGeneratorSecurityGroup:
      Type: AWS::ElastiCache::SecurityGroup
      Properties: 
        Description: ImageGenerator SecurityGroup
    
    ImageGeneratorCache:
      DependsOn:
        - ImageGeneratorSecurityGroup
      Type: AWS::ElastiCache::CacheCluster
      Properties: 
        CacheNodeType: cache.t2.small
        ClusterName: ImageGeneratorCache-${self:provider.stage}
        Engine: memcached
        CacheSecurityGroupNames:
          - Ref: ImageGeneratorSecurityGroup
        NumCacheNodes: 3

    ImageGeneratorDatabase:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ImageList-${self:provider.stage}
        AttributeDefinitions: 
          - AttributeName: filename
            AttributeType: S
        KeySchema: 
          - AttributeName: filename
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST 

functions:
  ImageGenerator:
    handler: index.imageGenerator
    layers:
      - { Ref: SourceLambdaLayer }
    environment:
      DYNAMODB_TABLE: ImageList-${self:provider.stage}
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ImageGeneratorQueue, Arn]
          batchSize: 1